# -*- coding: utf-8 -*-
p = 'REPORT_COLD.md'
s = open(p, encoding='utf-8').read()
old5 = "## 5. Where I disagree with the auditor's audits\n"
assert old5 in s
s = s.replace(old5, old5 + """Read only after §0–§4 and §6–§8 were written (diary). Files: AUDIT_FIRST_PASS_FLIGHT_1/2/3, AUDIT_FLIGHT_4, BAI_2003_READING_v1, BARRIDO_NOVEDAD_TEOREMA_D_v1.
**Where I agree.** On every link I agree with the auditor's grade: RT′ (and the citation error FLIGHT3 found in FLIGHT2), Φ, P-R1, B.1, C.0, C.4, Theorem D, the cost form, Theorem O, Theorem U, Theorem F steps 1–8, base cell → real cells, i = 0. My independent code reproduces his G1 (my G-L5, 87 360 entries) and G3 (my C4: λ ≤ 255, α ≤ 4, three prices), with the same zero failures. On Bai, the reading and the table gate coincide with mine (his first transcription failed for the same superscript reason I avoided by reading the rendered page). On priority I reach the same conclusion by partly different searches.
**Where I disagree (four points):**
1. **Integer splitting (AUDIT_FLIGHT_4 §2, «Integer splitting — CORRECT. No two adjacent blocks have equal non-integer means…»).** Equal means are not the only way the integer split can fail to be antitonic: adjacent blocks of means 3/2 and 5/4 split as (2, 1 | 2, 1, 1, 1) (my P-INT). The property the proof needs is **⌊μ_A⌋ ≥ ⌈μ_B⌉ for adjacent blocks**; it is true, and the same induction gives it (integer shifts d_A ≥ d_B preserve it; the central block 0 has neighbours of mean > 0 and < 0; the junction without merge has μ ≥ 0), and it holds in every cell I checked (1 559 985 sequences). So the step is right, but the justification printed and accepted is too narrow: **PRESENTATION, not CORRECT as written.**
2. **The statement as printed (AUDIT_FLIGHT_4 §4, copied into MISSION §1).** It says the exponents of «Smith₂ M» are the integer PAVA of x_D. They are not: they are **k + 2^k + κ(i−1, 2^k) + PAVA(x)_D** (the k from 2^k·coker M, the rest from the constant valuation of the cell). The auditor's own G1 compares «up to ONE constant per cell», so the constant was seen and then dropped in the printed theorem; and the formula needs a separate convention at i = 0 (m = −1). The theorem is true; the one-line statement is not, read literally (§1, S1–S3).
3. **Doty–Henke as the source of m_λ(n) (AUDIT_FLIGHT_4 §5 «to credit»; BARRIDO Entry 2 «Larsen 2405.16015, Doty–Henke math/0205186: tilting decomposition of V^{⊗n}…»).** Doty–Henke decompose L ⊗ L′ for two simple modules and factorise tilting modules (Lemma 1.4); they do **not** give the multiplicities of T(λ) in V^{⊗n}. The right citations are Donkin's tensor product theorem (characters) and Larsen 2024 §2, whose V^{⊗2} fusion rule I checked to give **exactly** the flights' multiplicities (P-LARSEN, 32/32 even n ≤ 64; control fires). BARRIDO's conclusion «m_λ(n) known» is right; the attribution should move from Doty–Henke to Donkin/Larsen (and Tubbenhauer–Wedrich, whom Larsen cites).
4. **Credit for the basis (not in the auditor's list).** The basis s_S = ∏(1 − x_i), in which the Laplacian is σ = U + 2D, is the Laplacian analogue of CSX §5, eq. (5) (the adjacency matrix in the monomial basis is diag(n − 2|I|) + inclusion), and is Gao et al.'s change of variables u_i = x_i − 1 (proof of their Prop. 2.5). The auditor asks to credit Gao et al.'s method in general; I would name these two places.
**Small notes (no disagreement of substance).** (a) AUDIT_FLIGHT_4 §1 says «No external cold reading yet»: this report is one. (b) BARRIDO Entry 3 gives CSX as DCC 84 (2017); I did not verify the journal reference. (c) The auditor's chain table (§4) correctly omits Theorem Z; MISSION's table lists Bier's basis in L3, but it is not a link of the final chain (my L3).
""")
open(p, 'w', encoding='utf-8').write(s)
print('ok')
